# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Lee SeungJin
title: Student
email: tmdwid2@gmail.com
# email_title: Email (Email title override)
phone: 010-6247-8856
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: false

github_username:  tmdwid2
instagram_username: @_promotion_lee

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://user-images.githubusercontent.com/115774345/197946725-fa6220d9-95d6-40ec-b421-ac5c06ab633d.jpg
about_content: | # this will include new lines to allow paragraphs


content:
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Hallym Univ.
        sub_title: **Major** BigData **Double Major** Contents-it
        caption: 2020 ~
        description: | # this will include new lines to allow paragraphs
          Description of qualification

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
